//! The console's flow tester: what a flow needs configured, the pending request it
//! holds between `/authorize` and its callback, and the checks it runs on what came
//! back.
//!
//! This module is the protocol half; [`crate::admin::flow`] is the HTML half. The
//! split is the same one the rest of the console keeps: a page may render a
//! [`Finding`], but it never decides what one is.
//!
//! Three properties are deliberate and are what make this safe to expose on a
//! console that is reachable from the internet:
//!
//! - **`state`, `nonce` and the PKCE verifier are generated here**, never taken
//!   from a form, and the row they live in is keyed by the *hash* of the state. A
//!   callback that cannot name a pending row is an error the page reports; it is
//!   also what stands in for a CSRF token on the callback, which an identity
//!   provider's `form_post` cannot carry.
//! - **The row is bound to the console session that created it** and deleted the
//!   moment it is used. Nothing that comes back -- no code, no token -- is ever
//!   written to the database or to the audit log.
//! - **The token exchange is a real HTTP request to our own token endpoint.** A
//!   debugger that bypassed the layer being debugged would eventually lie about it.

use anyhow::Context;
use serde_json::Value;

use crate::apps::{self, Application, RedirectPlatform};
use crate::config::PublicUrl;
use crate::db::DbPool;
use crate::routes::{Prompt, ResponseMode, ResponseType};
use crate::scopes::{self, Resource};
use crate::tenant::Tenant;
use crate::util::{b64url, half_hash, now, random_bytes, sha256_hex};

/// The console's own callback, under the public URL's path prefix. One fixed URI:
/// it has to be registered on the application being tested, so it must not depend
/// on the tenant or on the application.
pub const CALLBACK_PATH: &str = "/admin/flow/callback";

/// The absolute URI that must be registered as a redirect URI.
pub fn callback_uri(url: &PublicUrl) -> String {
    format!("{}{CALLBACK_PATH}", url.base())
}

/// How long a sent-but-unanswered flow test stays pending.
///
/// Invented: ten minutes, the authorization code's own lifetime. The row only
/// exists to redeem a code, so keeping it past the point where the code itself
/// would be refused buys nothing.
pub const PENDING_LIFETIME_SECS: i64 = 600;

/// Display name of the client the console registers on request. Named for what it
/// is, so it is recognisable in the applications list without this table.
pub const TEST_CLIENT_NAME: &str = "Flow tester (admin console)";

/// `details.purpose` on the audit rows this feature writes through another
/// section's event, so "why does this application have that redirect URI" has an
/// answer in the log.
pub const PURPOSE: &str = "flow_test";

/// Form and query field names, spelled once.
pub const APP_FIELD: &str = "app";
pub const RESPONSE_TYPE_FIELD: &str = "response_type";
pub const RESPONSE_MODE_FIELD: &str = "response_mode";
pub const SCOPE_FIELD: &str = "scope";
pub const PROMPT_FIELD: &str = "prompt";
pub const PASSWORD_GRANT_FIELD: &str = "password_grant";
pub const PLATFORM_FIELD: &str = "platform";

/// The scope a fresh page offers. `openid profile email` is the smallest request
/// that produces an ID token worth reading.
pub const DEFAULT_SCOPE: &str = "openid profile email";

// ---- what is being tested ----

/// The configuration the administrator has chosen on the landing page. Everything
/// here comes from a closed set or is free text that only ever reaches a request.
#[derive(Debug, Clone)]
pub struct Probe {
    pub response_type: ResponseType,
    pub response_mode: ResponseMode,
    pub scope: String,
    pub prompt: Option<Prompt>,
    /// Whether the password grant is part of what is being tested, which turns on
    /// the `allow_password_grant` requirement.
    pub password_grant: bool,
}

impl Default for Probe {
    fn default() -> Self {
        Self {
            response_type: ResponseType::Code,
            response_mode: ResponseMode::Query,
            scope: DEFAULT_SCOPE.to_string(),
            prompt: None,
            password_grant: false,
        }
    }
}

impl Probe {
    /// The response mode this response type should use, which is what the page
    /// offers before the administrator changes it: `form_post` as soon as a token
    /// travels in the response, because the console has no script to read a
    /// fragment with and a query string must never carry a token.
    pub fn default_mode(response_type: ResponseType) -> ResponseMode {
        if response_type.is_front_channel() {
            ResponseMode::FormPost
        } else {
            ResponseMode::Query
        }
    }

    /// PKCE is sent whenever there is a code to protect. Generated by the server,
    /// never by a form.
    pub fn uses_pkce(&self) -> bool {
        self.response_type.has_code()
    }
}

// ---- readiness ----

/// One thing a flow test needs. An enum rather than a list of strings so that a
/// requirement cannot be reported without a title and a place on the page.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Requirement {
    ServicePrincipal,
    Callback,
    Platform,
    ClientSecret,
    IdTokenToggle,
    AccessTokenToggle,
    OpenidScope,
    ResourceScope,
    Assignment,
    PasswordGrant,
    Delivery,
    Exchange,
}

impl Requirement {
    pub const ALL: &'static [Requirement] = &[
        Self::ServicePrincipal,
        Self::Callback,
        Self::Platform,
        Self::ClientSecret,
        Self::IdTokenToggle,
        Self::AccessTokenToggle,
        Self::OpenidScope,
        Self::ResourceScope,
        Self::Assignment,
        Self::PasswordGrant,
        Self::Delivery,
        Self::Exchange,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::ServicePrincipal => "service_principal",
            Self::Callback => "callback",
            Self::Platform => "platform",
            Self::ClientSecret => "client_secret",
            Self::IdTokenToggle => "allow_id_token_implicit",
            Self::AccessTokenToggle => "allow_access_token_implicit",
            Self::OpenidScope => "openid_scope",
            Self::ResourceScope => "resource_scope",
            Self::Assignment => "app_role_assignment_required",
            Self::PasswordGrant => "allow_password_grant",
            Self::Delivery => "delivery",
            Self::Exchange => "token_exchange",
        }
    }

    /// What the row says it is about.
    pub fn title(self) -> &'static str {
        match self {
            Self::ServicePrincipal => "Service principal in this tenant",
            Self::Callback => "Flow-test callback registered",
            Self::Platform => "Platform of that callback",
            Self::ClientSecret => "Client secret",
            Self::IdTokenToggle => "ID tokens through the front channel",
            Self::AccessTokenToggle => "Access tokens through the front channel",
            Self::OpenidScope => "The openid scope",
            Self::ResourceScope => "The requested scope resolves",
            Self::Assignment => "User assignment",
            Self::PasswordGrant => "Password grant (ROPC)",
            Self::Delivery => "How the response gets back here",
            Self::Exchange => "Who redeems the code",
        }
    }
}

/// Whether a requirement is met. `Note` is neither: it is something the
/// administrator has to know and cannot fix, and it never blocks the flow.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    Pass,
    Fail,
    Note,
}

impl Verdict {
    pub const ALL: &'static [Verdict] = &[Self::Pass, Self::Fail, Self::Note];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pass => "pass",
            Self::Fail => "fail",
            Self::Note => "note",
        }
    }

    /// The word shown in the pill.
    pub fn label(self) -> &'static str {
        match self {
            Self::Pass => "ready",
            Self::Fail => "missing",
            Self::Note => "note",
        }
    }
}

/// Where the remedy for a finding is. This module names the place; the page builds
/// the link, because console URLs are not this module's business.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Fix {
    /// The application's own page in the console.
    ApplicationPage,
    /// The callback section further down the flow tester's own page.
    CallbackSection,
    /// One of the boxes in the form at the top of this page.
    ThisForm,
}

impl Fix {
    pub const ALL: &'static [Fix] = &[Self::ApplicationPage, Self::CallbackSection, Self::ThisForm];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::ApplicationPage => "application_page",
            Self::CallbackSection => "callback_section",
            Self::ThisForm => "this_form",
        }
    }
}

/// One line of the readiness list: what is configured now, and what to do when it
/// is not what the chosen flow needs.
#[derive(Debug, Clone)]
pub struct Finding {
    pub requirement: Requirement,
    pub verdict: Verdict,
    /// What is configured, stated plainly.
    pub detail: String,
    /// What to change, and where. `None` when there is nothing to do.
    pub remedy: Option<String>,
    /// Where to go to do it, so the page can offer a link rather than only prose.
    pub fix: Option<Fix>,
}

impl Finding {
    fn new(requirement: Requirement, verdict: Verdict, detail: impl Into<String>) -> Self {
        Self {
            requirement,
            verdict,
            detail: detail.into(),
            remedy: None,
            fix: None,
        }
    }

    fn with_remedy(mut self, remedy: impl Into<String>) -> Self {
        self.remedy = Some(remedy.into());
        self
    }

    fn at(mut self, fix: Fix) -> Self {
        self.fix = Some(fix);
        self
    }
}

/// The answer to "why can I not test this yet".
#[derive(Debug, Clone)]
pub struct Readiness {
    pub findings: Vec<Finding>,
    /// Platform of the registered callback, when it is registered at all.
    pub platform: Option<RedirectPlatform>,
    /// Whether the console can complete the token exchange itself. False for a
    /// `web` client: it must authenticate, and only a hash of its secret is stored.
    pub can_exchange: bool,
}

impl Readiness {
    /// Nothing is missing. The start button appears only then.
    pub fn ready(&self) -> bool {
        !self.findings.iter().any(|f| f.verdict == Verdict::Fail)
    }

    pub fn missing(&self) -> usize {
        self.findings.iter().filter(|f| f.verdict == Verdict::Fail).count()
    }
}

/// Everything the readiness list needs to be computed from storage.
pub struct Subject<'a> {
    pub tenant: &'a Tenant,
    pub app: &'a Application,
    /// The signed-in administrator's own account id, when their account lives in
    /// this tenant. Used only to answer the assignment requirement for the most
    /// likely signing-in user; `None` means it is reported as uncheckable.
    pub admin_user_id: Option<&'a str>,
}

/// Work out, item by item, whether this application can run this flow.
///
/// Reads only. Every refusal the server would make is re-derived from the same
/// functions the server itself uses -- [`scopes::resolve`] for the scope,
/// [`apps::redirect_uris`] for the callback -- so the page cannot drift from the
/// endpoint it is describing.
pub async fn readiness(
    pool: &DbPool,
    url: &PublicUrl,
    subject: &Subject<'_>,
    probe: &Probe,
) -> anyhow::Result<Readiness> {
    let (tenant, app) = (subject.tenant, subject.app);
    let callback = callback_uri(url);
    let mut findings = Vec::new();

    // -- the service principal, which is what lets this tenant sign in to the app
    let sp = apps::service_principal(pool, &tenant.id, &app.app_id).await?;
    findings.push(match &sp {
        None => Finding::new(
            Requirement::ServicePrincipal,
            Verdict::Fail,
            format!("{} has no service principal in {}.", app.display_name, tenant.name),
        )
        .with_remedy("An application registered in another tenant needs a service principal here before anyone in this tenant can sign in to it."),
        Some(sp) if !sp.enabled => Finding::new(
            Requirement::ServicePrincipal,
            Verdict::Fail,
            "The service principal exists but is disabled, so every sign-in is refused.",
        )
        .with_remedy("Enable it before testing."),
        Some(_) => Finding::new(
            Requirement::ServicePrincipal,
            Verdict::Pass,
            format!("Enabled in {}.", tenant.name),
        ),
    });

    // -- the callback, and the platform it is registered under
    let registered = apps::redirect_uris(pool, app).await?;
    let platform = registered
        .iter()
        .find(|(_, uri)| apps::redirect_uri_matches(uri, &callback))
        .map(|(p, _)| *p);
    findings.push(match platform {
        Some(p) => Finding::new(
            Requirement::Callback,
            Verdict::Pass,
            format!("{callback} is registered under platform {}.", p.as_str()),
        ),
        None => Finding::new(
            Requirement::Callback,
            Verdict::Fail,
            format!("{callback} is not one of this application's redirect URIs, so the authorize request would be refused before it reached a sign-in page."),
        )
        .with_remedy(
            "Add it below, or on the application's own page. The console will not add it on its own: \
             a redirect URI is part of a registration, and a debug action must not change one silently.",
        )
        .at(Fix::CallbackSection),
    });
    findings.push(platform_finding(platform));

    // -- credentials. The console never has a secret value and never asks for one.
    //    A web client may authenticate with a certificate instead, so both count.
    let needs_credential = platform == Some(RedirectPlatform::Web) || probe.password_grant;
    let secret = apps::secrets(pool, app).await?.iter().any(|s| s.is_current(now()));
    let certificate = apps::key_credentials(pool, app)
        .await?
        .iter()
        .any(|c| c.is_current(now()));
    findings.push(match (needs_credential, secret, certificate) {
        (false, _, _) => Finding::new(
            Requirement::ClientSecret,
            Verdict::Note,
            "Not used by this flow: only a web client, and the password grant, authenticate at the token endpoint.",
        ),
        (true, false, false) => Finding::new(
            Requirement::ClientSecret,
            Verdict::Fail,
            "This client must authenticate at the token endpoint and has neither an unexpired client secret nor a current certificate credential.",
        )
        .with_remedy("Add a client secret on the application's page. You will never be asked to type one here.")
        .at(Fix::ApplicationPage),
        (true, s, c) => Finding::new(
            Requirement::ClientSecret,
            Verdict::Pass,
            format!(
                "{} registered and current. The value is not shown here and is not known to the console: only a SHA-256 hash of a secret is stored, and only the public part of a certificate.",
                match (s, c) {
                    (true, true) => "A client secret and a certificate credential are",
                    (true, false) => "A client secret is",
                    _ => "A certificate credential is",
                }
            ),
        ),
    });

    // -- the two front-channel toggles, named as the page that holds them names them
    findings.push(toggle_finding(
        Requirement::IdTokenToggle,
        probe.response_type.has_id_token(),
        app.allow_id_token_implicit,
        "id_token",
        "Allow implicit ID tokens",
    ));
    findings.push(toggle_finding(
        Requirement::AccessTokenToggle,
        probe.response_type.has_access_token(),
        app.allow_access_token_implicit,
        "token",
        "Allow implicit access tokens",
    ));

    // -- the scope, resolved by the same function the authorize endpoint uses
    let has_openid = probe.scope.split_whitespace().any(|s| s.eq_ignore_ascii_case("openid"));
    findings.push(match (probe.response_type.has_id_token(), has_openid) {
        (true, true) | (false, true) => Finding::new(
            Requirement::OpenidScope,
            Verdict::Pass,
            "Requested, so an ID token is issued.",
        ),
        (true, false) => Finding::new(
            Requirement::OpenidScope,
            Verdict::Fail,
            "The response type asks for an id_token, which requires the openid scope.",
        )
        .with_remedy("Add openid to the scope above.")
        .at(Fix::ThisForm),
        (false, false) => Finding::new(
            Requirement::OpenidScope,
            Verdict::Note,
            "Not requested. The flow will return an access token and no ID token.",
        ),
    });

    let grant = scopes::resolve(pool, tenant, &probe.scope).await;
    let resource_sp = match &grant {
        Ok(g) => {
            let detail = match &g.resource {
                Resource::Graph => format!(
                    "Resolves to the Microsoft Graph audience {}; scp will be {}.",
                    g.resource.audience(),
                    list(&g.scp)
                ),
                Resource::App { app, .. } => format!(
                    "Resolves to {} (audience {}); scp will be {}.",
                    app.display_name,
                    g.resource.audience(),
                    list(&g.scp)
                ),
            };
            findings.push(Finding::new(Requirement::ResourceScope, Verdict::Pass, detail));
            match &g.resource {
                Resource::App { sp, .. } => Some(sp.clone()),
                Resource::Graph => None,
            }
        }
        Err(err) => {
            findings.push(
                Finding::new(
                    Requirement::ResourceScope,
                    Verdict::Fail,
                    format!("AADSTS{}: {}", err.code.code(), err.message),
                )
                .with_remedy(
                    "A delegated permission has to be exposed and enabled on the API it names, \
                     and one request may target only one resource.",
                )
                .at(Fix::ThisForm),
            );
            None
        }
    };

    // -- assignment. Enforced on the *client's* service principal at sign-in; the
    //    resource's own requirement is reported because this server does not apply
    //    it, which is a difference worth seeing in a debugger.
    findings.push(assignment_finding(pool, subject, sp.as_ref(), resource_sp.as_ref()).await?);

    if probe.password_grant {
        findings.push(if app.allow_password_grant {
            Finding::new(
                Requirement::PasswordGrant,
                Verdict::Pass,
                "allow_password_grant is on, so the token endpoint accepts grant_type=password for this application.",
            )
            .with_remedy(
                "The console does not run this flow: it would have to send both the client secret, which it cannot read, \
                 and a user's password, which it will not collect. The request to run by hand is shown below.",
            )
        } else {
            Finding::new(
                Requirement::PasswordGrant,
                Verdict::Fail,
                "allow_password_grant is off, so grant_type=password is refused for this application.",
            )
            .with_remedy("Turn on \"Allow the resource owner password grant (ROPC)\" in the Grants section of the application's page.")
            .at(Fix::ApplicationPage)
        });
    }

    // -- how the response gets back, and who redeems the code
    findings.push(delivery_finding(probe));
    let can_exchange = matches!(
        platform,
        Some(RedirectPlatform::Spa) | Some(RedirectPlatform::PublicClient)
    );
    findings.push(exchange_finding(probe, platform, can_exchange));

    Ok(Readiness {
        findings,
        platform,
        can_exchange,
    })
}

fn list(values: &[String]) -> String {
    if values.is_empty() {
        "empty".to_string()
    } else {
        values.join(" ")
    }
}

fn platform_finding(platform: Option<RedirectPlatform>) -> Finding {
    match platform {
        None => Finding::new(
            Requirement::Platform,
            Verdict::Note,
            "Unknown until the callback is registered. The platform it is registered under decides the client rules.",
        ),
        Some(RedirectPlatform::Web) => Finding::new(
            Requirement::Platform,
            Verdict::Note,
            "web: a confidential client. It must authenticate at the token endpoint with its client secret or a certificate, and PKCE is optional.",
        ),
        Some(RedirectPlatform::Spa) => Finding::new(
            Requirement::Platform,
            Verdict::Note,
            "spa: PKCE is required, a secret must not be sent, and the token endpoint accepts the redemption only as a cross-origin request.",
        ),
        Some(RedirectPlatform::PublicClient) => Finding::new(
            Requirement::Platform,
            Verdict::Note,
            "publicClient: no secret, and no cross-origin requirement. PKCE is sent anyway, because a public client has nothing else binding the code to this request.",
        ),
    }
}

/// One of the two front-channel toggles. `needed` is whether the chosen response
/// type contains the value this toggle gates.
fn toggle_finding(
    requirement: Requirement,
    needed: bool,
    enabled: bool,
    response_value: &str,
    checkbox: &str,
) -> Finding {
    match (needed, enabled) {
        (false, _) => Finding::new(
            requirement,
            Verdict::Note,
            format!("Not required: this response type does not contain {response_value}."),
        ),
        (true, true) => Finding::new(requirement, Verdict::Pass, format!("On, so a response_type containing {response_value} is allowed.")),
        (true, false) => Finding::new(
            requirement,
            Verdict::Fail,
            format!("Off, so a response_type containing {response_value} is refused with AADSTS700054 before any sign-in page is shown."),
        )
        .with_remedy(format!("Tick \"{checkbox}\" in the Grants section of the application's page."))
        .at(Fix::ApplicationPage),
    }
}

async fn assignment_finding(
    pool: &DbPool,
    subject: &Subject<'_>,
    client_sp: Option<&apps::ServicePrincipal>,
    resource_sp: Option<&apps::ServicePrincipal>,
) -> anyhow::Result<Finding> {
    let client_requires = client_sp.is_some_and(|sp| sp.app_role_assignment_required);
    let resource_requires = resource_sp.is_some_and(|sp| sp.app_role_assignment_required);
    if !client_requires && !resource_requires {
        return Ok(Finding::new(
            Requirement::Assignment,
            Verdict::Note,
            "Neither this application nor the API it asks for requires an app role assignment, so any enabled user in this tenant can sign in.",
        ));
    }
    let resource_note = if resource_requires {
        " The API's own service principal also requires assignment; this server enforces that on the client's service principal only, so it will not refuse the token."
    } else {
        ""
    };
    if !client_requires {
        return Ok(Finding::new(
            Requirement::Assignment,
            Verdict::Note,
            format!("This application does not require an assignment.{resource_note}"),
        ));
    }
    let Some(admin_user_id) = subject.admin_user_id else {
        return Ok(Finding::new(
            Requirement::Assignment,
            Verdict::Note,
            format!(
                "This application requires an app role assignment, so whoever signs in must hold one directly or through a group. \
                 Your own account is not in this tenant, so the console cannot check it for you.{resource_note}"
            ),
        ));
    };
    let sp = client_sp.expect("client_requires implies a service principal");
    let assigned = apps::user_is_assigned(pool, &sp.id, admin_user_id).await?;
    Ok(if assigned {
        Finding::new(
            Requirement::Assignment,
            Verdict::Pass,
            format!("Required, and your own account holds one. Anybody else signing in needs one too.{resource_note}"),
        )
    } else {
        Finding::new(
            Requirement::Assignment,
            Verdict::Fail,
            format!("Required, and your own account does not hold one, so signing in as yourself would be refused with AADSTS50105.{resource_note}"),
        )
        .with_remedy("Assign a user or a group to an app role of this application, in the Role assignments section of its page.")
        .at(Fix::ApplicationPage)
    })
}

fn delivery_finding(probe: &Probe) -> Finding {
    match (probe.response_mode, probe.response_type.is_front_channel()) {
        (ResponseMode::Query, true) => Finding::new(
            Requirement::Delivery,
            Verdict::Fail,
            "response_mode=query cannot be used with a response type that carries a token; the server refuses it, and a token in a query string would end up in logs and Referer headers.",
        )
        .with_remedy("Choose form_post.")
        .at(Fix::ThisForm),
        (ResponseMode::Query, false) => Finding::new(
            Requirement::Delivery,
            Verdict::Pass,
            "The code comes back as a query string on a redirect to the console's callback.",
        ),
        (ResponseMode::FormPost, _) => Finding::new(
            Requirement::Delivery,
            Verdict::Pass,
            "The response is POSTed to the console's callback as a form body, which is how the console can read a token at all.",
        ),
        (ResponseMode::Fragment, _) => Finding::new(
            Requirement::Delivery,
            Verdict::Note,
            "A URL fragment never reaches the server, and the console's content security policy has no script to copy one into a form. \
             The flow will not be captured here: the console shows you the authorize URL to open yourself, and the response stays in your address bar.",
        )
        .with_remedy("Choose form_post to have the values arrive here instead.")
        .at(Fix::ThisForm),
    }
}

fn exchange_finding(probe: &Probe, platform: Option<RedirectPlatform>, can_exchange: bool) -> Finding {
    if !probe.response_type.has_code() {
        return Finding::new(
            Requirement::Exchange,
            Verdict::Note,
            "There is no code in this response, so there is nothing to redeem: everything the flow produces arrives in the front channel.",
        );
    }
    match (platform, can_exchange) {
        (_, true) => Finding::new(
            Requirement::Exchange,
            Verdict::Pass,
            "The console redeems the code itself, with a real HTTP request to this server's token endpoint, and shows you the request and the response.",
        ),
        (Some(RedirectPlatform::Web), _) => Finding::new(
            Requirement::Exchange,
            Verdict::Note,
            "A web client has to authenticate to redeem the code, and the console cannot: only a SHA-256 hash of the client secret is stored, by design. \
             The front channel is still tested end to end, and the exact token request is shown for you to run.",
        )
        .with_remedy(
            "To exercise the redemption too, use this tenant's flow tester client, which is registered as a public client and needs no secret.",
        )
        .at(Fix::CallbackSection),
        (None, _) => Finding::new(
            Requirement::Exchange,
            Verdict::Note,
            "Unknown until the callback is registered: the platform it is registered under decides whether the client has to authenticate.",
        ),
        (Some(_), false) => Finding::new(
            Requirement::Exchange,
            Verdict::Note,
            "The console cannot redeem the code for this client.",
        ),
    }
}

// ---- the pending flow ----

/// A flow test that has been sent and not yet answered.
#[derive(Debug, Clone)]
pub struct Pending {
    pub tenant_id: String,
    pub client_app_id: String,
    pub response_type: ResponseType,
    pub response_mode: ResponseMode,
    pub scope: String,
    pub redirect_uri: String,
    pub nonce: String,
    pub code_verifier: Option<String>,
    pub authorize_url: String,
}

/// What [`start`] produced: the `state` the browser carries, and the URL to send it to.
pub struct Started {
    pub state: String,
    pub authorize_url: String,
}

/// Build the authorize request, and remember what it has to come back with.
///
/// `admin_session` is the hash of the console session cookie, which is what binds
/// the pending row to the administrator who created it.
pub async fn start(
    pool: &DbPool,
    url: &PublicUrl,
    tenant: &Tenant,
    client_app_id: &str,
    probe: &Probe,
    admin_session: &str,
) -> anyhow::Result<Started> {
    let built = build_request(url, tenant, client_app_id, probe);
    let ts = now();
    // No scheduler in this process: clear what has expired while writing anyway,
    // the way `admin::session::create` does.
    sqlx::query(crate::db::q(pool, "DELETE FROM flow_tests WHERE expires_at < ?"))
        .bind(ts)
        .execute(pool)
        .await?;
    sqlx::query(crate::db::q(
        pool,
        "INSERT INTO flow_tests (state_hash, tenant_id, client_app_id, admin_session, response_type, response_mode,
                                 scope, redirect_uri, nonce, code_verifier, authorize_url, created_at, expires_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
    ))
    .bind(sha256_hex(built.state.as_bytes()))
    .bind(&tenant.id)
    .bind(client_app_id)
    .bind(admin_session)
    .bind(probe.response_type.as_str())
    .bind(probe.response_mode.as_str())
    .bind(&probe.scope)
    .bind(&built.redirect_uri)
    .bind(&built.nonce)
    .bind(built.code_verifier.as_deref())
    .bind(&built.authorize_url)
    .bind(ts)
    .bind(ts + PENDING_LIFETIME_SECS)
    .execute(pool)
    .await?;
    Ok(Started {
        state: built.state,
        authorize_url: built.authorize_url,
    })
}

/// The authorize request, before anything is stored. Separated so that the
/// fragment mode -- which is never captured, so never stored -- can be shown
/// without writing a row that would only expire.
pub struct BuiltRequest {
    pub state: String,
    pub nonce: String,
    pub code_verifier: Option<String>,
    pub redirect_uri: String,
    pub authorize_url: String,
}

pub fn build_request(url: &PublicUrl, tenant: &Tenant, client_app_id: &str, probe: &Probe) -> BuiltRequest {
    // 32 bytes each: `state` is the only thing standing between this callback and a
    // forged one, and the verifier has to be at least 43 characters.
    let state = b64url(&random_bytes(32));
    let nonce = b64url(&random_bytes(32));
    let code_verifier = probe.uses_pkce().then(|| b64url(&random_bytes(32)));
    let redirect_uri = callback_uri(url);

    let mut authorize = url::Url::parse(&url.tenant_url(&tenant.id, "oauth2/v2.0/authorize"))
        .expect("the public URL parses, so a path under it does");
    {
        let mut q = authorize.query_pairs_mut();
        q.append_pair("client_id", client_app_id);
        q.append_pair("response_type", probe.response_type.as_str());
        q.append_pair("response_mode", probe.response_mode.as_str());
        q.append_pair("redirect_uri", &redirect_uri);
        q.append_pair("scope", &probe.scope);
        q.append_pair("state", &state);
        // Always sent, even for a plain code flow: it is what lets the result page
        // check that the ID token belongs to this request.
        q.append_pair("nonce", &nonce);
        if let Some(verifier) = &code_verifier {
            q.append_pair("code_challenge", &pkce_challenge(verifier));
            q.append_pair("code_challenge_method", PKCE_METHOD);
        }
        if let Some(prompt) = probe.prompt {
            q.append_pair("prompt", prompt.as_str());
        }
    }
    BuiltRequest {
        state,
        nonce,
        code_verifier,
        redirect_uri,
        authorize_url: authorize.into(),
    }
}

/// The only code challenge method the tester uses. `plain` exists in the server
/// for compatibility; a debugger has no reason to send it.
pub const PKCE_METHOD: &str = "S256";

pub fn pkce_challenge(verifier: &str) -> String {
    use base64::Engine;
    use sha2::Digest;
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(sha2::Sha256::digest(verifier.as_bytes()))
}

/// Take the pending flow this `state` names, if it belongs to this console session
/// and has not expired. Single use: the row is deleted, and a second callback with
/// the same state finds nothing.
pub async fn take(pool: &DbPool, admin_session: &str, state: &str) -> anyhow::Result<Option<Pending>> {
    let hash = sha256_hex(state.as_bytes());
    let row: Option<PendingRow> = sqlx::query_as(crate::db::q(
        pool,
        "SELECT tenant_id, client_app_id, response_type, response_mode, scope, redirect_uri, nonce,
                code_verifier, authorize_url FROM flow_tests
         WHERE state_hash = ? AND admin_session = ? AND expires_at > ?",
    ))
    .bind(&hash)
    .bind(admin_session)
    .bind(now())
    .fetch_optional(pool)
    .await?;
    let Some(row) = row else { return Ok(None) };
    // Race-safe single use: only the request that removes the row may use it.
    let removed = sqlx::query(crate::db::q(
        pool,
        "DELETE FROM flow_tests WHERE state_hash = ? AND admin_session = ?",
    ))
    .bind(&hash)
    .bind(admin_session)
    .execute(pool)
    .await?
    .rows_affected();
    if removed != 1 {
        return Ok(None);
    }
    // A stored value this build cannot read is a refusal, not a default: the same
    // rule `stored_platform` follows for a grant.
    let response_type = ResponseType::parse(&row.response_type)
        .with_context(|| format!("pending flow test has an unknown response_type {:?}", row.response_type))?;
    let response_mode = ResponseMode::parse(&row.response_mode)
        .with_context(|| format!("pending flow test has an unknown response_mode {:?}", row.response_mode))?;
    Ok(Some(Pending {
        tenant_id: row.tenant_id,
        client_app_id: row.client_app_id,
        response_type,
        response_mode,
        scope: row.scope,
        redirect_uri: row.redirect_uri,
        nonce: row.nonce,
        code_verifier: row.code_verifier,
        authorize_url: row.authorize_url,
    }))
}

/// The stored shape of a [`Pending`], before the two closed sets are parsed.
#[derive(sqlx::FromRow)]
struct PendingRow {
    tenant_id: String,
    client_app_id: String,
    response_type: String,
    response_mode: String,
    scope: String,
    redirect_uri: String,
    nonce: String,
    code_verifier: Option<String>,
    authorize_url: String,
}

// ---- the tenant's own flow tester client ----

/// This tenant's flow tester client, if it has one and it still exists.
pub async fn test_client(pool: &DbPool, tenant_id: &str) -> anyhow::Result<Option<Application>> {
    let mut conn = pool.acquire().await?;
    test_client_in(&mut conn, tenant_id).await
}

pub(crate) async fn test_client_in(conn: &mut crate::db::Conn, tenant_id: &str) -> anyhow::Result<Option<Application>> {
    let row: Option<(String,)> = sqlx::query_as(crate::db::qc(
        &conn,
        "SELECT app_id FROM flow_test_clients WHERE tenant_id = ?",
    ))
    .bind(tenant_id)
    .fetch_optional(&mut *conn)
    .await?;
    let Some((app_id,)) = row else { return Ok(None) };
    // Deleted in the applications section: the row stays, the client is gone, and
    // the console offers to create another.
    Ok(apps::find_in(&mut *conn, &app_id)
        .await?
        .filter(|a| a.tenant_id == tenant_id))
}

/// What registering the flow tester client came to.
#[derive(Debug)]
pub struct TestClient {
    pub application: Application,
    /// False when the tenant already had one, which is returned unchanged.
    pub created: bool,
}

/// Register this tenant's flow tester client: an ordinary application whose only
/// redirect URI is the console's callback, as a **public client**, so that a flow
/// can be exercised end to end -- including the code redemption -- without a
/// secret and without touching any real registration.
pub async fn create_test_client(pool: &DbPool, url: &PublicUrl, tenant: &Tenant) -> anyhow::Result<Application> {
    let mut conn = pool.acquire().await?;
    let mut tx = sqlx::Connection::begin(&mut *conn).await?;
    let made = create_test_client_in(&mut *tx, &callback_uri(url), tenant).await?;
    tx.commit().await?;
    Ok(made.application)
}

/// [`create_test_client`] on a connection, with the callback URI given. A mapping
/// left behind by a deleted application is cleared first, or it would block this.
pub(crate) async fn create_test_client_in(
    conn: &mut crate::db::Conn,
    callback: &str,
    tenant: &Tenant,
) -> anyhow::Result<TestClient> {
    if let Some(existing) = test_client_in(&mut *conn, &tenant.id).await? {
        return Ok(TestClient {
            application: existing,
            created: false,
        });
    }
    forget_test_client_in(&mut *conn, &tenant.id).await?;
    let created = apps::create_in(&mut *conn, tenant, TEST_CLIENT_NAME).await?;
    apps::add_redirect_uri_in(
        &mut *conn,
        &created.application,
        RedirectPlatform::PublicClient,
        callback,
    )
    .await?;
    sqlx::query(crate::db::qc(
        &conn,
        "INSERT INTO flow_test_clients (tenant_id, app_id, created_at) VALUES (?, ?, ?)",
    ))
    .bind(&tenant.id)
    .bind(&created.application.app_id)
    .bind(now())
    .execute(&mut *conn)
    .await?;
    Ok(TestClient {
        application: created.application,
        created: true,
    })
}

/// Forget the mapping, for the one case it can go stale: the application was
/// deleted in the applications section and another is being registered.
pub async fn forget_test_client(pool: &DbPool, tenant_id: &str) -> anyhow::Result<()> {
    let mut conn = pool.acquire().await?;
    forget_test_client_in(&mut conn, tenant_id).await
}

pub(crate) async fn forget_test_client_in(conn: &mut crate::db::Conn, tenant_id: &str) -> anyhow::Result<()> {
    sqlx::query(crate::db::qc(
        &conn,
        "DELETE FROM flow_test_clients WHERE tenant_id = ?",
    ))
    .bind(tenant_id)
    .execute(&mut *conn)
    .await?;
    Ok(())
}

// ---- the token exchange ----

/// A request the tester made, and what came back, exactly as it went over the
/// wire. This is the whole point of using a real client: what is displayed is what
/// a client would have sent and received.
#[derive(Debug, Clone, Default)]
pub struct HttpCall {
    pub url: String,
    pub headers: Vec<(String, String)>,
    pub body: String,
    pub status: Option<u16>,
    pub response: Option<String>,
    /// Set when the request never got an answer: TLS, DNS, a refused connection.
    pub transport_error: Option<String>,
}

impl HttpCall {
    /// The parsed response body, when it was JSON.
    pub fn json(&self) -> Option<Value> {
        serde_json::from_str(self.response.as_deref()?).ok()
    }
}

/// The method is always POST, but it is shown on the page, so it is named here.
pub const TOKEN_METHOD: &str = "POST";
const FORM_CONTENT_TYPE: &str = "application/x-www-form-urlencoded";

/// How long the tester waits for its own token endpoint. Invented: ten seconds.
/// Long enough for a cold connection, short enough that a wedged endpoint shows as
/// a timeout on the page instead of hanging the console.
const EXCHANGE_TIMEOUT_SECS: u64 = 10;

/// Redeem the code at our own token endpoint, over HTTP.
///
/// Never panics and never returns `Err`: a failed exchange is a result the page has
/// to show, not an error page. The reply is returned verbatim.
pub async fn exchange(url: &PublicUrl, pending: &Pending, code: &str, platform: RedirectPlatform) -> HttpCall {
    let endpoint = url.tenant_url(&pending.tenant_id, "oauth2/v2.0/token");
    // In its own scope: the serializer is not `Send`, and this function holds its
    // result across an await.
    let body = {
        let mut form = url::form_urlencoded::Serializer::new(String::new());
        form.append_pair("grant_type", crate::routes::GrantType::AuthorizationCode.as_str());
        form.append_pair("client_id", &pending.client_app_id);
        form.append_pair("code", code);
        form.append_pair("redirect_uri", &pending.redirect_uri);
        form.append_pair("scope", &pending.scope);
        if let Some(verifier) = &pending.code_verifier {
            form.append_pair("code_verifier", verifier);
        }
        form.finish()
    };

    let mut headers = vec![(reqwest::header::CONTENT_TYPE.to_string(), FORM_CONTENT_TYPE.to_string())];
    // An spa client may only redeem cross-origin, so the request has to look like
    // one. A web or public client must *not* send Origin: the token endpoint
    // refuses cross-origin redemption for anything but an spa.
    if platform == RedirectPlatform::Spa
        && let Ok(parsed) = url::Url::parse(&pending.redirect_uri)
    {
        headers.push((
            reqwest::header::ORIGIN.to_string(),
            parsed.origin().ascii_serialization(),
        ));
    }

    let mut call = HttpCall {
        url: endpoint.clone(),
        headers: headers.clone(),
        body: body.clone(),
        ..Default::default()
    };

    // No proxy: this is a request to ourselves, and an ambient proxy variable must
    // not quietly put a middlebox between the console and the endpoint it is
    // testing.
    let client = match reqwest::Client::builder()
        .no_proxy()
        .timeout(std::time::Duration::from_secs(EXCHANGE_TIMEOUT_SECS))
        .build()
    {
        Ok(c) => c,
        Err(e) => {
            call.transport_error = Some(e.to_string());
            return call;
        }
    };
    let mut request = client.post(&endpoint).body(body);
    for (name, value) in &headers {
        request = request.header(name.as_str(), value.as_str());
    }
    match request.send().await {
        Ok(resp) => {
            call.status = Some(resp.status().as_u16());
            call.response = Some(resp.text().await.unwrap_or_else(|e| format!("<unreadable body: {e}>")));
        }
        Err(e) => call.transport_error = Some(e.to_string()),
    }
    call
}

// ---- reading what came back ----

/// Claim names the result page checks. Spelled once each.
pub const CLAIM_NONCE: &str = "nonce";
pub const CLAIM_C_HASH: &str = "c_hash";
pub const CLAIM_AT_HASH: &str = "at_hash";
pub const CLAIM_ISS: &str = "iss";
pub const CLAIM_AUD: &str = "aud";
pub const CLAIM_EXP: &str = "exp";

/// A JWT, taken apart for display. `signature` is the outcome of verifying it
/// against this deployment's published signing keys.
pub struct DecodedToken {
    pub header: Value,
    pub claims: Value,
    pub signature: Result<(), String>,
}

/// Split a compact JWS and decode its two JSON parts. The signature is not checked
/// here: [`crate::keys::KeyStore::verify`] does that, and a token that fails it
/// still has to be displayed.
pub fn decode_parts(token: &str) -> anyhow::Result<(Value, Value)> {
    use base64::Engine;
    let mut parts = token.split('.');
    let header = parts.next().unwrap_or_default();
    let claims = parts.next().unwrap_or_default();
    anyhow::ensure!(parts.next().is_some(), "not a compact JWS: expected three parts");
    let decode = |part: &str| -> anyhow::Result<Value> {
        let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(part)
            .context("a JWT part is not base64url")?;
        serde_json::from_slice(&bytes).context("a JWT part is not JSON")
    };
    Ok((decode(header)?, decode(claims)?))
}

/// One thing checked on a token that came back.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Check {
    Signature,
    Issuer,
    Audience,
    Expiry,
    Nonce,
    CodeHash,
    AccessTokenHash,
}

impl Check {
    pub const ALL: &'static [Check] = &[
        Self::Signature,
        Self::Issuer,
        Self::Audience,
        Self::Expiry,
        Self::Nonce,
        Self::CodeHash,
        Self::AccessTokenHash,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Signature => "signature",
            Self::Issuer => CLAIM_ISS,
            Self::Audience => CLAIM_AUD,
            Self::Expiry => CLAIM_EXP,
            Self::Nonce => CLAIM_NONCE,
            Self::CodeHash => CLAIM_C_HASH,
            Self::AccessTokenHash => CLAIM_AT_HASH,
        }
    }

    pub fn title(self) -> &'static str {
        match self {
            Self::Signature => "Signature",
            Self::Issuer => "iss",
            Self::Audience => "aud",
            Self::Expiry => "exp",
            Self::Nonce => "nonce",
            Self::CodeHash => "c_hash",
            Self::AccessTokenHash => "at_hash",
        }
    }
}

/// The outcome of one check, with what was seen.
#[derive(Debug, Clone)]
pub struct Observation {
    pub check: Check,
    pub verdict: Verdict,
    pub detail: String,
}

impl Observation {
    fn new(check: Check, verdict: Verdict, detail: impl Into<String>) -> Self {
        Self {
            check,
            verdict,
            detail: detail.into(),
        }
    }
}

/// What an ID token is checked against.
pub struct Expected<'a> {
    pub issuer: &'a str,
    pub audience: &'a str,
    pub nonce: Option<&'a str>,
    /// The code delivered in the same response, for `c_hash`.
    pub code: Option<&'a str>,
    /// The access token delivered in the same response, for `at_hash`.
    pub access_token: Option<&'a str>,
}

/// Check an ID token's binding to this request. Pure, so it is testable without a
/// server: every input is already in hand by the time it is called.
pub fn check_id_token(token: &DecodedToken, expected: &Expected<'_>) -> Vec<Observation> {
    let claims = &token.claims;
    let mut out = vec![signature_observation(token)];
    out.push(string_claim(claims, Check::Issuer, CLAIM_ISS, expected.issuer));
    out.push(audience_matches(claims, expected.audience));
    out.push(expiry(claims));
    out.push(
        match (expected.nonce, claims.get(CLAIM_NONCE).and_then(Value::as_str)) {
            (Some(want), Some(got)) if got == want => {
                Observation::new(Check::Nonce, Verdict::Pass, "Matches the nonce this request sent.")
            }
            (Some(_), Some(_)) => Observation::new(
                Check::Nonce,
                Verdict::Fail,
                "Does not match the nonce this request sent: this token belongs to a different request.",
            ),
            (Some(_), None) => Observation::new(
                Check::Nonce,
                Verdict::Fail,
                "Absent, although the request sent a nonce. An ID token must echo it.",
            ),
            (None, _) => Observation::new(Check::Nonce, Verdict::Note, "The request sent no nonce."),
        },
    );
    out.push(half_hash_check(
        Check::CodeHash,
        claims.get(CLAIM_C_HASH).and_then(Value::as_str),
        expected.code,
        "code",
    ));
    out.push(half_hash_check(
        Check::AccessTokenHash,
        claims.get(CLAIM_AT_HASH).and_then(Value::as_str),
        expected.access_token,
        "access token",
    ));
    out
}

/// Check an access token, which carries no `nonce` and no hash claims. Our access
/// tokens are JWTs; another server's might be opaque, which is why the caller only
/// gets here once it decoded one.
pub fn check_access_token(token: &DecodedToken, issuer: &str, audience: Option<&str>) -> Vec<Observation> {
    let claims = &token.claims;
    let mut out = vec![signature_observation(token)];
    out.push(string_claim(claims, Check::Issuer, CLAIM_ISS, issuer));
    out.push(match audience {
        Some(want) => audience_matches(claims, want),
        None => match claims.get(CLAIM_AUD) {
            Some(aud) => Observation::new(
                Check::Audience,
                Verdict::Note,
                format!("{aud}. The scope did not name a resource, so there is nothing to compare it to."),
            ),
            None => Observation::new(Check::Audience, Verdict::Fail, "Absent."),
        },
    });
    out.push(expiry(claims));
    out
}

fn signature_observation(token: &DecodedToken) -> Observation {
    match &token.signature {
        Ok(()) => Observation::new(
            Check::Signature,
            Verdict::Pass,
            "Verified against this deployment's published signing keys.",
        ),
        Err(e) => Observation::new(
            Check::Signature,
            Verdict::Fail,
            format!("Does not verify against this deployment's published signing keys: {e}"),
        ),
    }
}

fn string_claim(claims: &Value, check: Check, name: &str, expected: &str) -> Observation {
    match claims.get(name).and_then(Value::as_str) {
        Some(got) if got == expected => Observation::new(check, Verdict::Pass, got.to_string()),
        Some(got) => Observation::new(check, Verdict::Fail, format!("{got}, expected {expected}")),
        None => Observation::new(check, Verdict::Fail, format!("Absent, expected {expected}")),
    }
}

/// `aud` may be a string or an array of strings (RFC 7519); ours is a string.
fn audience_matches(claims: &Value, expected: &str) -> Observation {
    let got = claims.get(CLAIM_AUD);
    let matches = match got {
        Some(Value::String(s)) => s == expected,
        Some(Value::Array(items)) => items.iter().any(|i| i.as_str() == Some(expected)),
        _ => false,
    };
    match (got, matches) {
        (Some(aud), true) => Observation::new(Check::Audience, Verdict::Pass, aud.to_string()),
        (Some(aud), false) => Observation::new(Check::Audience, Verdict::Fail, format!("{aud}, expected {expected}")),
        (None, _) => Observation::new(Check::Audience, Verdict::Fail, format!("Absent, expected {expected}")),
    }
}

fn expiry(claims: &Value) -> Observation {
    match claims.get(CLAIM_EXP).and_then(Value::as_i64) {
        Some(exp) => {
            let left = exp - now();
            if left > 0 {
                Observation::new(
                    Check::Expiry,
                    Verdict::Pass,
                    format!("{} ({left}s from now)", crate::admin::view::ts(exp)),
                )
            } else {
                Observation::new(
                    Check::Expiry,
                    Verdict::Fail,
                    format!("{}, which is {}s in the past", crate::admin::view::ts(exp), -left),
                )
            }
        }
        None => Observation::new(Check::Expiry, Verdict::Fail, "Absent."),
    }
}

/// `c_hash` and `at_hash` are the same construction over different values.
fn half_hash_check(check: Check, claimed: Option<&str>, value: Option<&str>, what: &str) -> Observation {
    match (claimed, value) {
        (Some(claimed), Some(value)) => {
            let want = half_hash(value);
            if claimed == want {
                Observation::new(
                    check,
                    Verdict::Pass,
                    format!("{claimed}, which is the left half of SHA-256 over the {what} in this response."),
                )
            } else {
                Observation::new(
                    check,
                    Verdict::Fail,
                    format!("{claimed}, but the {what} in this response hashes to {want}."),
                )
            }
        }
        (Some(claimed), None) => Observation::new(
            check,
            Verdict::Fail,
            format!(
                "{claimed} is present although no {what} came back in the same response, so there is nothing it can bind."
            ),
        ),
        (None, Some(_)) => Observation::new(
            check,
            Verdict::Note,
            format!(
                "Absent. Required only when the {what} travels in the same response as the ID token, \
                 which is the hybrid flow."
            ),
        ),
        (None, None) => Observation::new(check, Verdict::Note, format!("Absent, and no {what} to bind.")),
    }
}

/// How a flow test ended, for the one audit row that records it. Never any of the
/// material: this is the whole of what the log learns.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// The callback could not be matched to a pending flow test.
    StateUnknown,
    /// The server answered the authorize request with an OAuth error.
    AuthorizeError,
    /// Delivered, and the console did not try to redeem (nothing to redeem, or it
    /// cannot authenticate as this client).
    FrontChannelOnly,
    /// The code was redeemed.
    Exchanged,
    /// The redemption was attempted and failed.
    ExchangeFailed,
}

impl Outcome {
    pub const ALL: &'static [Outcome] = &[
        Self::StateUnknown,
        Self::AuthorizeError,
        Self::FrontChannelOnly,
        Self::Exchanged,
        Self::ExchangeFailed,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::StateUnknown => "state_unknown",
            Self::AuthorizeError => "authorize_error",
            Self::FrontChannelOnly => "front_channel_only",
            Self::Exchanged => "exchanged",
            Self::ExchangeFailed => "exchange_failed",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn decoded(claims: Value) -> DecodedToken {
        DecodedToken {
            header: json!({ "alg": "RS256" }),
            claims,
            signature: Ok(()),
        }
    }

    fn verdict(obs: &[Observation], check: Check) -> Verdict {
        obs.iter().find(|o| o.check == check).expect("checked").verdict
    }

    #[test]
    fn every_requirement_and_check_has_a_distinct_name() {
        let mut seen = std::collections::HashSet::new();
        for r in Requirement::ALL {
            assert!(seen.insert(r.as_str()), "two requirements are both {}", r.as_str());
            assert!(!r.title().is_empty());
        }
        let mut seen = std::collections::HashSet::new();
        for c in Check::ALL {
            assert!(seen.insert(c.as_str()), "two checks are both {}", c.as_str());
        }
        let mut seen = std::collections::HashSet::new();
        for o in Outcome::ALL {
            assert!(seen.insert(o.as_str()), "two outcomes are both {}", o.as_str());
        }
        let mut seen = std::collections::HashSet::new();
        for f in Fix::ALL {
            assert!(seen.insert(f.as_str()), "two places are both {}", f.as_str());
        }
    }

    #[test]
    fn a_nonce_that_does_not_match_is_a_failure_not_a_shrug() {
        let token = decoded(json!({ "nonce": "theirs", "iss": "i", "aud": "a", "exp": now() + 60 }));
        let expected = Expected {
            issuer: "i",
            audience: "a",
            nonce: Some("ours"),
            code: None,
            access_token: None,
        };
        let obs = check_id_token(&token, &expected);
        assert_eq!(verdict(&obs, Check::Nonce), Verdict::Fail);
        // And a matching one passes, so the test is about the comparison.
        let token = decoded(json!({ "nonce": "ours", "iss": "i", "aud": "a", "exp": now() + 60 }));
        assert_eq!(verdict(&check_id_token(&token, &expected), Check::Nonce), Verdict::Pass);
    }

    #[test]
    fn c_hash_and_at_hash_are_checked_against_the_values_in_the_response() {
        let code = "the-code";
        let access = "the.access.token";
        let token = decoded(json!({
            "nonce": "ours",
            "iss": "i",
            "aud": "a",
            "exp": now() + 60,
            "c_hash": half_hash(code),
            "at_hash": half_hash(access),
        }));
        let expected = Expected {
            issuer: "i",
            audience: "a",
            nonce: Some("ours"),
            code: Some(code),
            access_token: Some(access),
        };
        let obs = check_id_token(&token, &expected);
        assert_eq!(verdict(&obs, Check::CodeHash), Verdict::Pass);
        assert_eq!(verdict(&obs, Check::AccessTokenHash), Verdict::Pass);

        // The same token against a different code must fail, not pass quietly.
        let other = Expected {
            code: Some("another-code"),
            ..expected
        };
        assert_eq!(verdict(&check_id_token(&token, &other), Check::CodeHash), Verdict::Fail);
    }

    #[test]
    fn issuer_audience_and_expiry_are_compared_and_an_expired_token_fails() {
        let token = decoded(json!({ "iss": "wrong", "aud": ["x"], "exp": now() - 1, "nonce": "ours" }));
        let expected = Expected {
            issuer: "right",
            audience: "a",
            nonce: Some("ours"),
            code: None,
            access_token: None,
        };
        let obs = check_id_token(&token, &expected);
        assert_eq!(verdict(&obs, Check::Issuer), Verdict::Fail);
        assert_eq!(verdict(&obs, Check::Audience), Verdict::Fail);
        assert_eq!(verdict(&obs, Check::Expiry), Verdict::Fail);
    }

    #[test]
    fn an_array_audience_containing_the_client_matches() {
        let token = decoded(json!({ "iss": "i", "aud": ["other", "a"], "exp": now() + 60 }));
        let obs = check_access_token(&token, "i", Some("a"));
        assert_eq!(verdict(&obs, Check::Audience), Verdict::Pass);
    }

    #[test]
    fn a_bad_signature_is_reported_as_a_failed_check_rather_than_hidden() {
        let mut token = decoded(json!({ "iss": "i", "aud": "a", "exp": now() + 60 }));
        token.signature = Err("unknown kid".into());
        let obs = check_access_token(&token, "i", Some("a"));
        assert_eq!(verdict(&obs, Check::Signature), Verdict::Fail);
    }

    #[test]
    fn the_default_response_mode_keeps_tokens_out_of_a_query_string() {
        assert_eq!(Probe::default_mode(ResponseType::Code), ResponseMode::Query);
        for rt in [ResponseType::IdToken, ResponseType::Token, ResponseType::IdTokenToken] {
            assert_eq!(Probe::default_mode(rt), ResponseMode::FormPost, "{rt:?}");
        }
        assert_eq!(Probe::default_mode(ResponseType::CodeIdToken), ResponseMode::FormPost);
    }

    #[test]
    fn pkce_is_generated_for_every_response_type_that_carries_a_code() {
        for rt in ResponseType::ALL {
            let probe = Probe {
                response_type: *rt,
                ..Probe::default()
            };
            assert_eq!(probe.uses_pkce(), rt.has_code(), "{rt:?}");
        }
    }

    #[test]
    fn the_pkce_challenge_is_the_s256_one_the_token_endpoint_recomputes() {
        // The same construction `user_grants::authorization_code` checks against.
        use base64::Engine;
        use sha2::Digest;
        let verifier = "a-verifier-long-enough-to-be-accepted-by-the-server";
        let want = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(sha2::Sha256::digest(verifier.as_bytes()));
        assert_eq!(pkce_challenge(verifier), want);
    }

    #[test]
    fn a_decoded_jwt_yields_its_header_and_claims() {
        use base64::Engine;
        let enc = |v: &Value| base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(serde_json::to_vec(v).unwrap());
        let token = format!(
            "{}.{}.signature",
            enc(&json!({ "alg": "RS256", "kid": "k" })),
            enc(&json!({ "sub": "u" }))
        );
        let (header, claims) = decode_parts(&token).unwrap();
        assert_eq!(header["kid"], "k");
        assert_eq!(claims["sub"], "u");
        assert!(decode_parts("not-a-jwt").is_err());
    }
}
